import { expect, test } from "bun:test"
import { mkdtemp, readFile, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"

import { parseJsonc } from "../src/jsonc"
import { generate, GenerateError } from "../src/generate"
import { p0Fixture, exampleA } from "./fixtures/cfnext-json"
import { splitGenerated, isDirtyGenerated } from "../src/generate/hash"

async function tmpProject(): Promise<string> {
  return mkdtemp(join(tmpdir(), "cfnext-gen-"))
}

test("generate writes hashed wrangler with build.command and no previews", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(p0Fixture, null, 2))
  const result = await generate(dir)
  expect(result.skipped).toBe(false)
  const text = await readFile(join(dir, "wrangler.jsonc"), "utf8")
  expect(text).toContain("@generated by cfnext")
  expect(isDirtyGenerated(text)).toBe(false)
  const wrangler = parseJsonc<{
    build?: { command?: string }
    previews?: unknown
    d1_databases?: Array<{ binding: string; preview_database_id?: string }>
    r2_buckets?: Array<{ bucket_name: string }>
    ai?: { binding: string }
  }>(splitGenerated(text).body)
  expect(wrangler.build?.command).toBe("bun --bun next build")
  expect(wrangler.previews).toBeUndefined()
  expect(wrangler.d1_databases?.[0]?.binding).toBe("DB")
  expect(wrangler.r2_buckets?.[0]?.bucket_name).toBe("demo-bucket")
  expect(wrangler.ai?.binding).toBe("AI")
  expect(await readFile(join(dir, "cfnext.config.generated.ts"), "utf8")).toContain("export default config")
})

test("generate refuses Example A unimplemented paths", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(exampleA, null, 2))
  await expect(generate(dir)).rejects.toBeInstanceOf(GenerateError)
})

test("echo // hack makes wrangler dirty", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(p0Fixture, null, 2))
  await generate(dir)
  const path = join(dir, "wrangler.jsonc")
  await writeFile(path, `${await readFile(path, "utf8")}// hack\n`)
  expect(isDirtyGenerated(await readFile(path, "utf8"))).toBe(true)
  await expect(generate(dir)).rejects.toThrow(/edited/)
  await generate(dir, { force: true })
})

test("implicit generate skips when cfnext.json is missing", async () => {
  const dir = await tmpProject()
  const result = await generate(dir, { implicit: true })
  expect(result.skipped).toBe(true)
})

test("legacy hand-written wrangler is not overwritten without cfnext.json", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "wrangler.jsonc"), `{ "name": "legacy", "main": "worker.ts", "compatibility_date": "2026-08-16" }\n`)
  const result = await generate(dir, { implicit: true })
  expect(result.skipped).toBe(true)
  expect(await readFile(join(dir, "wrangler.jsonc"), "utf8")).toContain(`"name": "legacy"`)
})

test("generated wrangler without json is an error", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "wrangler.jsonc"), "// @generated by cfnext@0.1.0\n// @hash sha256:dead\n{}\n")
  await expect(generate(dir, { implicit: true })).rejects.toThrow(/required to regenerate/)
})

test("env.staging merges d1 by binding name and omits name", async () => {
  const dir = await tmpProject()
  await writeFile(
    join(dir, "cfnext.json"),
    JSON.stringify(
      {
        ...p0Fixture,
        bindings: {
          d1: [
            {
              binding: "DB",
              databaseName: "demo-db",
              id: "11111111-1111-1111-1111-111111111111",
              migrationsDir: "migrations",
            },
          ],
        },
        env: {
          staging: {
            bindings: { d1: [{ binding: "DB", id: "22222222-2222-2222-2222-222222222222" }] },
          },
        },
      },
      null,
      2,
    ),
  )
  await generate(dir)
  const wrangler = parseJsonc<{
    env?: { staging?: { name?: string; d1_databases?: Array<{ database_id?: string; binding: string }> } }
  }>(splitGenerated(await readFile(join(dir, "wrangler.jsonc"), "utf8")).body)
  expect(wrangler.env?.staging?.name).toBeUndefined()
  expect(wrangler.env?.staging?.d1_databases?.[0]?.database_id).toBe("22222222-2222-2222-2222-222222222222")
  expect(wrangler.env?.staging?.d1_databases?.[0]?.binding).toBe("DB")
})

test("env.preview is rejected", async () => {
  const dir = await tmpProject()
  await writeFile(
    join(dir, "cfnext.json"),
    JSON.stringify({ name: "demo", target: "workers", env: { preview: { vars: { X: "1" } } } }, null, 2),
  )
  await expect(generate(dir)).rejects.toThrow(/illegal/)
})
