import { expect, test } from "bun:test"
import { readFileSync } from "node:fs"
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { tmpdir } from "node:os"

import { parseJsonc } from "../src/jsonc"
import { generate, GenerateError } from "../src/generate"
import { p0Fixture, exampleA, exampleB } from "./fixtures/cfnext-json"
import { splitGenerated, isDirtyGenerated } from "../src/generate/hash"

async function tmpProject(): Promise<string> {
  return mkdtemp(join(tmpdir(), "cfnext-gen-"))
}

test("generate writes hashed wrangler with build.command and no previews", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(p0Fixture, null, 2))
  const result = await generate(dir)
  expect(result.skipped).toBe(false)
  const text = await readFile(join(dir, "wrangler.jsonc"), "utf8")
  expect(text).toContain("@generated by cfnext")
  expect(isDirtyGenerated(text)).toBe(false)
  const wrangler = parseJsonc<{
    build?: { command?: string }
    previews?: unknown
    d1_databases?: Array<{ binding: string; preview_database_id?: string }>
    r2_buckets?: Array<{ bucket_name: string }>
    ai?: { binding: string }
  }>(splitGenerated(text).body)
  expect(wrangler.build?.command).toBe("bun --bun next build")
  expect(wrangler.previews).toBeUndefined()
  expect(wrangler.d1_databases?.[0]?.binding).toBe("DB")
  expect(wrangler.r2_buckets?.[0]?.bucket_name).toBe("demo-bucket")
  expect(wrangler.ai?.binding).toBe("AI")
  expect(await readFile(join(dir, "cfnext.config.generated.ts"), "utf8")).toContain("export default config")
})

test("generate Example A emits send_email and images", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(exampleA, null, 2))
  await writeFile(
    join(dir, "email.ts"),
    `export async function email() { }\n`,
  )
  await generate(dir)
  const wrangler = parseJsonc<{
    send_email?: Array<{ name: string; allowed_sender_addresses?: string[] }>
    images?: { binding: string }
  }>(splitGenerated(await readFile(join(dir, "wrangler.jsonc"), "utf8")).body)
  expect(wrangler.send_email).toEqual([
    { name: "EMAIL", allowed_sender_addresses: ["noreply@acme.com"] },
  ])
  expect(wrangler.images).toEqual({ binding: "IMAGES" })

  const wranglerPkg = Bun.resolveSync("wrangler/package.json", import.meta.dir)
  const schema = JSON.parse(readFileSync(join(dirname(wranglerPkg), "config-schema.json"), "utf8")) as object
  const Ajv = (await import("ajv")).default
  const ajv = new Ajv({ strict: false, allErrors: true })
  const validate = ajv.compile(schema)
  expect(validate(wrangler), JSON.stringify(validate.errors, null, 2)).toBe(true)
})

test("generate Example B emits AI search, agent DO, and no model vars", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(exampleB, null, 2))
  await mkdir(join(dir, "agents"), { recursive: true })
  await mkdir(join(dir, "workflows"), { recursive: true })
  await writeFile(join(dir, "agents/ResearchAgent.ts"), "export class ResearchAgent {}\n")
  await writeFile(join(dir, "workflows/IngestWorkflow.ts"), "export class IngestWorkflow {}\n")
  await generate(dir)
  const wrangler = parseJsonc<{
    ai?: { binding: string }
    ai_search?: Array<{ binding: string; instance_name: string }>
    durable_objects?: { bindings?: Array<{ name: string; class_name: string }> }
    vars?: Record<string, string>
    workflows?: Array<{ class_name: string }>
  }>(splitGenerated(await readFile(join(dir, "wrangler.jsonc"), "utf8")).body)
  expect(wrangler.ai?.binding).toBe("AI")
  expect(wrangler.ai_search).toEqual([{ binding: "AI_SEARCH", instance_name: "docs" }])
  expect(wrangler.durable_objects?.bindings).toEqual([
    { name: "RESEARCH_AGENT", class_name: "ResearchAgent" },
  ])
  expect(wrangler.workflows?.some((row) => row.class_name === "IngestWorkflow")).toBe(true)
  expect(JSON.stringify(wrangler.vars ?? {})).not.toContain("@cf/")

  const models = await readFile(join(dir, ".cloudflare/generated/models.ts"), "utf8")
  expect(models).toContain("@cf/meta/llama-3.3-70b-instruct-fp8-fast")

  const wranglerPkg = Bun.resolveSync("wrangler/package.json", import.meta.dir)
  const schema = JSON.parse(readFileSync(join(dirname(wranglerPkg), "config-schema.json"), "utf8")) as object
  const Ajv = (await import("ajv")).default
  const ajv = new Ajv({ strict: false, allErrors: true })
  const validate = ajv.compile(schema)
  expect(validate(wrangler), JSON.stringify(validate.errors, null, 2)).toBe(true)
})

test("echo // hack makes wrangler dirty", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(p0Fixture, null, 2))
  await generate(dir)
  const path = join(dir, "wrangler.jsonc")
  await writeFile(path, `${await readFile(path, "utf8")}// hack\n`)
  expect(isDirtyGenerated(await readFile(path, "utf8"))).toBe(true)
  await expect(generate(dir)).rejects.toThrow(/edited/)
  await generate(dir, { force: true })
  expect(isDirtyGenerated(await readFile(path, "utf8"))).toBe(false)
})

test("generate --check throws when wrangler is stale", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify(p0Fixture, null, 2))
  await generate(dir)
  await writeFile(join(dir, "cfnext.json"), JSON.stringify({ ...p0Fixture, name: "renamed" }, null, 2))
  await expect(generate(dir, { check: true })).rejects.toThrow(/out of date/)
})

test("generate dryRun returns text without writing", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "cfnext.json"), JSON.stringify({ name: "demo", target: "workers" }, null, 2))
  const result = await generate(dir, { dryRun: true })
  expect(result.wranglerText).toContain("@generated")
  expect(await Bun.file(join(dir, "wrangler.jsonc")).exists()).toBe(false)
})

test("env overlay unimplemented fields are rejected", async () => {
  const dir = await tmpProject()
  await writeFile(
    join(dir, "cfnext.json"),
    JSON.stringify(
      { name: "demo", target: "workers", env: { staging: { agents: [{ className: "ResearchAgent" }] } } },
      null,
      2,
    ),
  )
  await expect(generate(dir)).rejects.toThrow(/env\.staging\.agents/)
})

test("implicit generate skips when cfnext.json is missing", async () => {
  const dir = await tmpProject()
  const result = await generate(dir, { implicit: true })
  expect(result.skipped).toBe(true)
})

test("legacy hand-written wrangler is not overwritten without cfnext.json", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "wrangler.jsonc"), `{ "name": "legacy", "main": "worker.ts", "compatibility_date": "2026-08-16" }\n`)
  const result = await generate(dir, { implicit: true })
  expect(result.skipped).toBe(true)
  expect(await readFile(join(dir, "wrangler.jsonc"), "utf8")).toContain(`"name": "legacy"`)
})

test("generated wrangler without json is an error", async () => {
  const dir = await tmpProject()
  await writeFile(join(dir, "wrangler.jsonc"), "// @generated by cfnext@0.1.0\n// @hash sha256:dead\n{}\n")
  await expect(generate(dir, { implicit: true })).rejects.toThrow(/required to regenerate/)
})

test("env.staging merges d1 by binding name and omits name", async () => {
  const dir = await tmpProject()
  await writeFile(
    join(dir, "cfnext.json"),
    JSON.stringify(
      {
        ...p0Fixture,
        bindings: {
          d1: [
            {
              binding: "DB",
              databaseName: "demo-db",
              id: "11111111-1111-1111-1111-111111111111",
              migrationsDir: "migrations",
            },
          ],
        },
        env: {
          staging: {
            bindings: { d1: [{ binding: "DB", id: "22222222-2222-2222-2222-222222222222" }] },
          },
        },
      },
      null,
      2,
    ),
  )
  await generate(dir)
  const wrangler = parseJsonc<{
    env?: { staging?: { name?: string; d1_databases?: Array<{ database_id?: string; binding: string }> } }
  }>(splitGenerated(await readFile(join(dir, "wrangler.jsonc"), "utf8")).body)
  expect(wrangler.env?.staging?.name).toBeUndefined()
  expect(wrangler.env?.staging?.d1_databases?.[0]?.database_id).toBe("22222222-2222-2222-2222-222222222222")
  expect(wrangler.env?.staging?.d1_databases?.[0]?.binding).toBe("DB")
})

test("env.preview is rejected", async () => {
  const dir = await tmpProject()
  await writeFile(
    join(dir, "cfnext.json"),
    JSON.stringify({ name: "demo", target: "workers", env: { preview: { vars: { X: "1" } } } }, null, 2),
  )
  await expect(generate(dir)).rejects.toThrow(/illegal/)
})
