import { createHash } from "node:crypto"

export const GENERATED_MARKER = "@generated by cfnext"

export function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex")
}

export function splitGenerated(text: string): {
  generated: boolean
  hash: string | null
  body: string
} {
  const normalized = text.replace(/\r\n/g, "\n")
  if (!normalized.startsWith("// @generated")) {
    return { generated: false, hash: null, body: normalized }
  }
  const lines = normalized.split("\n")
  let hash: string | null = null
  let i = 0
  for (; i < lines.length; i++) {
    const line = lines[i]!
    if (!line.startsWith("//")) break
    const match = line.match(/^\/\/ @hash sha256:([0-9a-f]+)\s*$/)
    if (match) hash = match[1]!
  }
  return { generated: true, hash, body: lines.slice(i).join("\n") }
}

export function stampGenerated(body: string, version: string, source = "cfnext.json"): string {
  const hash = sha256(body)
  return `// @generated by cfnext@${version}\n// @source ${source}\n// @hash sha256:${hash}\n${body}`
}

export function isDirtyGenerated(text: string): boolean {
  const { generated, hash, body } = splitGenerated(text)
  if (!generated || !hash) return true
  return sha256(body) !== hash
}
