import { existsSync } from "node:fs"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

import type { CfnextJson, CfnextModelAlias } from "../schema"
import { GenerateError } from "./errors"

export const MODELS_FILE = ".cloudflare/generated/models.ts"
export const MODELS_CLIENT_FILE = ".cloudflare/generated/models.client.ts"

export type ResolvedModel = {
  alias: string
  id: string
  public: boolean
}

export function resolveModelEntry(value: CfnextModelAlias): { id: string; public: boolean } {
  if (typeof value === "string") return { id: value, public: false }
  return { id: value.id, public: value.public === true }
}

export function resolveModels(json: CfnextJson): ResolvedModel[] {
  const models = json.ai?.models
  if (!models) return []
  return Object.entries(models).map(([alias, value]) => {
    const resolved = resolveModelEntry(value)
    return { alias, id: resolved.id, public: resolved.public }
  })
}

function renderModelsModule(entries: ResolvedModel[], exportName: "models" | "publicModels"): string {
  const typeName = exportName === "models" ? "ModelAlias" : "PublicModelAlias"
  const body = entries.map((entry) => `  ${JSON.stringify(entry.alias)}: ${JSON.stringify(entry.id)},`).join("\n")
  return `// @generated by cfnext. Do not edit.
export const ${exportName} = {
${body}
} as const

export type ${typeName} = keyof typeof ${exportName}
`
}

async function writeGeneratedFile(
  path: string,
  text: string,
  opts: { dryRun?: boolean; check?: boolean },
  staleMessage: string,
): Promise<void> {
  const prev = existsSync(path) ? await readFile(path, "utf8") : null
  if (opts.check && prev !== text) {
    throw new GenerateError(staleMessage)
  }
  if (!opts.dryRun && !opts.check) {
    await mkdir(join(path, ".."), { recursive: true })
    await writeFile(path, text)
  }
}

export async function writeModels(
  projectDir: string,
  json: CfnextJson,
  opts: { dryRun?: boolean; check?: boolean } = {},
): Promise<{ server: string | null; client: string | null }> {
  const models = resolveModels(json)
  if (models.length === 0) return { server: null, client: null }
  const server = renderModelsModule(models, "models")
  await writeGeneratedFile(
    join(projectDir, MODELS_FILE),
    server,
    opts,
    "generated models.ts is out of date. Run `cfnext generate`.",
  )
  const publicModels = models.filter((entry) => entry.public)
  if (publicModels.length === 0) return { server, client: null }
  const client = renderModelsModule(publicModels, "publicModels")
  await writeGeneratedFile(
    join(projectDir, MODELS_CLIENT_FILE),
    client,
    opts,
    "generated models.client.ts is out of date. Run `cfnext generate`.",
  )
  return { server, client }
}
