import { existsSync } from "node:fs"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

import type { CfnextJson } from "../schema"
import { GenerateError } from "./errors"

export const IMAGE_LOADER_JSON = ".cloudflare/generated/image-loader.json"
export const IMAGE_LOADER_FILE = ".cloudflare/generated/image-loader.ts"

export type ImageLoaderGenerated = {
  kind: "cdn-cgi" | "imagedelivery"
  zoneOrigin?: string
  accountHash?: string
  remotePatterns?: Array<Record<string, unknown>>
}

export function imageLoaderConfig(json: CfnextJson): ImageLoaderGenerated | null {
  const loader = json.media?.images?.loader
  if (!loader?.enabled) return null
  const kind = loader.kind ?? "cdn-cgi"
  if (kind === "cdn-cgi" && !loader.zoneOrigin) {
    throw new GenerateError(
      "media.images.loader.kind cdn-cgi requires zoneOrigin. Run `cfnext add image-loader --kind cdn-cgi --zone-origin https://example.com`.",
    )
  }
  if (kind === "imagedelivery" && !loader.accountHash) {
    throw new GenerateError(
      "media.images.loader.kind imagedelivery requires accountHash. Run `cfnext add image-loader --kind imagedelivery --account-hash <hash>`.",
    )
  }
  return {
    kind,
    ...(loader.zoneOrigin ? { zoneOrigin: loader.zoneOrigin } : {}),
    ...(loader.accountHash ? { accountHash: loader.accountHash } : {}),
    ...(loader.remotePatterns?.length ? { remotePatterns: loader.remotePatterns } : {}),
  }
}

export function renderImageLoaderModule(config: ImageLoaderGenerated): string {
  return `// @generated by cfnext. Do not edit.
import { buildCfnextImageUrl, type CfnextImageLoaderConfig } from "cfnext/image-loader"

const config = ${JSON.stringify(config, null, 2)} satisfies CfnextImageLoaderConfig

export default function cfnextImageLoader({
  src,
  width,
  quality,
}: {
  src: string
  width: number
  quality?: number
}): string {
  return buildCfnextImageUrl({ src, width, quality }, config)
}
`
}

export async function writeImageLoader(
  projectDir: string,
  json: CfnextJson,
  opts: { dryRun?: boolean; check?: boolean } = {},
): Promise<{ json: string | null; module: string | null }> {
  const config = imageLoaderConfig(json)
  if (!config) return { json: null, module: null }
  const jsonText = `${JSON.stringify(config, null, 2)}\n`
  const moduleText = renderImageLoaderModule(config)
  const jsonPath = join(projectDir, IMAGE_LOADER_JSON)
  const modulePath = join(projectDir, IMAGE_LOADER_FILE)
  const prevJson = existsSync(jsonPath) ? await readFile(jsonPath, "utf8") : null
  const prevModule = existsSync(modulePath) ? await readFile(modulePath, "utf8") : null
  const changed = prevJson !== jsonText || prevModule !== moduleText
  if (opts.check && changed) {
    throw new GenerateError("generated image loader is out of date. Run `cfnext generate`.")
  }
  if (!opts.dryRun && !opts.check) {
    await mkdir(join(projectDir, ".cloudflare/generated"), { recursive: true })
    await writeFile(jsonPath, jsonText)
    await writeFile(modulePath, moduleText)
  }
  return { json: jsonText, module: moduleText }
}
