import { writeFile } from "node:fs/promises"
import { join } from "node:path"

import type { CfnextConfig } from "../config"

export const RUNTIME_CONFIG_FILE = "cfnext.config.generated.ts"

export function renderRuntimeConfig(
  config: CfnextConfig,
  hooksImport: { shells: string } | null,
): string {
  const protect = hooksImport
    ? `{
    prefixes: ${JSON.stringify(config.protect.prefixes)},
    signInPath: ${JSON.stringify(config.protect.signInPath)},
    sessionCookiePattern: ${JSON.stringify(config.protect.sessionCookiePattern)},
    shells: ${hooksImport.shells}(),
  }`
    : JSON.stringify(config.protect, null, 2).replace(/\n/g, "\n  ")

  const hookLine = hooksImport
    ? `import { ${hooksImport.shells} } from "./cfnext.hooks"\n`
    : ""

  return `// @generated by cfnext. Do not edit.
import type { CfnextConfig } from "cfnext"
${hookLine}
const config = {
  name: ${JSON.stringify(config.name)},
  target: ${JSON.stringify(config.target)},
  protect: ${protect},
  images: ${JSON.stringify(config.images)},
  securityHeaders: ${config.securityHeaders},
} satisfies CfnextConfig

export default config
`
}

export async function writeRuntimeConfig(
  projectDir: string,
  config: CfnextConfig,
  hooksImport: { shells: string } | null,
): Promise<string> {
  const path = join(projectDir, RUNTIME_CONFIG_FILE)
  await writeFile(path, renderRuntimeConfig(config, hooksImport))
  return path
}
