import { existsSync } from "node:fs"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { join } from "node:path"

import type { CfnextJson } from "../schema"
import { GenerateError } from "./errors"

export const GENERATED_WORKER = ".cloudflare/generated/worker.ts"
export const GENERATED_HANDLERS = ".cloudflare/generated/handlers.ts"

export function renderGeneratedWorker(): string {
  return `// @generated by cfnext
import * as user from "../../worker"
import * as extra from "./handlers"
import { asExportedHandler, composeWorker } from "cfnext/worker/compose"

export default composeWorker(asExportedHandler(user.default), extra)
export * from "../../worker"
export * from "./handlers"
`
}

function handlerExports(json: CfnextJson): string[] {
  const lines: string[] = []
  if (json.email?.routing?.enabled) {
    lines.push(`export { email } from "../../email"`)
  }
  if (json.bindings?.queues?.some((item) => item.consume)) {
    lines.push(`export { queue } from "../../queue"`)
  }
  if (json.cron?.length) {
    lines.push(`export { scheduled } from "../../scheduled"`)
  }
  for (const item of json.workflows ?? []) {
    lines.push(`export { ${item.className} } from "../../workflows/${item.className}"`)
  }
  for (const item of json.durableObjects ?? []) {
    lines.push(`export { ${item.className} } from "../../durable-objects/${item.className}"`)
  }
  for (const item of json.agents ?? []) {
    lines.push(`export { ${item.className} } from "../../agents/${item.className}"`)
  }
  return lines
}

export function renderGeneratedHandlers(json: CfnextJson): string {
  const lines = handlerExports(json)
  if (lines.length === 0) return `// @generated by cfnext\nexport {}\n`
  return `// @generated by cfnext\n${lines.join("\n")}\n`
}

function exportedNames(source: string): string[] {
  const names = new Set<string>()
  for (const match of source.matchAll(/export\s+(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_]\w*)/g)) {
    if (match[1]) names.add(match[1])
  }
  for (const match of source.matchAll(/export\s*\{([^}]+)\}/g)) {
    for (const part of (match[1] ?? "").split(",")) {
      const trimmed = part.trim()
      if (!trimmed || trimmed === "default") continue
      const exported = trimmed.split(/\s+as\s+/).pop()?.trim()
      if (exported && exported !== "default") names.add(exported)
    }
  }
  return [...names]
}

export function requiredStubs(json: CfnextJson): Array<{ path: string; hint: string }> {
  const stubs: Array<{ path: string; hint: string }> = []
  if (json.email?.routing?.enabled) {
    stubs.push({ path: "email.ts", hint: "cfnext add email --inbound" })
  }
  if (json.bindings?.queues?.some((item) => item.consume)) {
    stubs.push({ path: "queue.ts", hint: "cfnext add queue --consume" })
  }
  if (json.cron?.length) {
    stubs.push({ path: "scheduled.ts", hint: 'cfnext add cron --expr "..."' })
  }
  for (const item of json.workflows ?? []) {
    stubs.push({
      path: `workflows/${item.className}.ts`,
      hint: `cfnext add workflow --class ${item.className}`,
    })
  }
  for (const item of json.durableObjects ?? []) {
    stubs.push({
      path: `durable-objects/${item.className}.ts`,
      hint: `cfnext add do --class ${item.className}`,
    })
  }
  for (const item of json.agents ?? []) {
    stubs.push({
      path: `agents/${item.className}.ts`,
      hint: `cfnext add agent --class ${item.className}`,
    })
  }
  return stubs
}

export function assertStubsExist(projectDir: string, json: CfnextJson): void {
  for (const stub of requiredStubs(json)) {
    if (!existsSync(join(projectDir, stub.path))) {
      throw new GenerateError(`Missing ${stub.path}. Re-run \`${stub.hint}\` or create the file.`)
    }
  }
}

export async function assertNoExportCollision(projectDir: string, json: CfnextJson): Promise<void> {
  const workerPath = join(projectDir, "worker.ts")
  if (!existsSync(workerPath)) return
  const workerNames = exportedNames(await readFile(workerPath, "utf8"))
  const extraNames: string[] = []
  if (json.email?.routing?.enabled) extraNames.push("email")
  if (json.bindings?.queues?.some((item) => item.consume)) extraNames.push("queue")
  if (json.cron?.length) extraNames.push("scheduled")
  for (const item of json.workflows ?? []) extraNames.push(item.className)
  for (const item of json.durableObjects ?? []) extraNames.push(item.className)
  for (const item of json.agents ?? []) extraNames.push(item.className)
  const clash = extraNames.filter((name) => workerNames.includes(name))
  if (clash.length > 0) {
    throw new GenerateError(
      `worker.ts and generated handlers both export: ${clash.join(", ")}. Move the class to its stub or rename one.`,
    )
  }
}

export async function writeGeneratedWorker(
  projectDir: string,
  json: CfnextJson,
  opts: { dryRun?: boolean; check?: boolean } = {},
): Promise<{ worker: string; handlers: string }> {
  assertStubsExist(projectDir, json)
  await assertNoExportCollision(projectDir, json)
  const worker = renderGeneratedWorker()
  const handlers = renderGeneratedHandlers(json)
  const workerPath = join(projectDir, GENERATED_WORKER)
  const handlersPath = join(projectDir, GENERATED_HANDLERS)
  const prevWorker = existsSync(workerPath) ? await readFile(workerPath, "utf8") : null
  const prevHandlers = existsSync(handlersPath) ? await readFile(handlersPath, "utf8") : null
  const changed = prevWorker !== worker || prevHandlers !== handlers
  if (opts.check && changed) {
    throw new GenerateError("generated worker is out of date. Run `cfnext generate`.")
  }
  if (!opts.dryRun && !opts.check) {
    await mkdir(join(projectDir, ".cloudflare/generated"), { recursive: true })
    await writeFile(workerPath, worker)
    await writeFile(handlersPath, handlers)
  }
  return { worker, handlers }
}
