/**
 * Workers-target execution for Next edge-runtime routes (e.g. API route
 * handlers with `runtime = "edge"`).
 *
 * A Turbopack edge entry registers its handler into `self._ENTRIES[key]`,
 * but only after every chunk it lists in `otherChunks` has been imported
 * (they feed the synchronous TURBOPACK module registry). At build time we
 * copy the entry plus the transitive chunk closure, emit a per-route index
 * module that imports siblings first and the entry last, and regenerate the
 * generated handlers module with an `edgeFetch` dispatcher; composeWorker()
 * tries it before falling through to the static-asset worker.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises"
import { extname, join, relative } from "node:path"

import { OUT_DIR } from "./constants"
import { GENERATED_HANDLERS } from "./generate/worker"

export type EdgeRouteEntry = {
  pathname: string
  filePath?: string
  id?: string
  entryKey?: string
  handlerExport?: string
  assets?: Record<string, string>
}

function slug(pathname: string): string {
  const s = pathname.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "")
  return s || "root"
}

function patternFor(pathname: string): string {
  const parts = pathname.split("/").filter(Boolean)
  const rx = parts
    .map((part) => {
      if (part.startsWith("[...")) return "(.+)"
      if (part.startsWith("[")) return "[^/]+"
      return part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    })
    .join("/")
  return `^/${rx}$`
}

/** Extract `otherChunks:["chunks/x._.js", ...]` entries from a chunk body. */
function otherChunksOf(body: string): string[] {
  const out: string[] = []
  const re = /otherChunks:\s*\[([^\]]*)\]/g
  let m: RegExpExecArray | null
  while ((m = re.exec(body))) {
    const inner = m[1] ?? ""
    const strRe = /"([^"]+)"/g
    let s: RegExpExecArray | null
    while ((s = strRe.exec(inner))) out.push(s[1]!)
  }
  return out
}

async function collectChunkClosure(
  entryPath: string,
): Promise<Array<{ srcAbs: string; relName: string }>> {
  const baseDir = join(entryPath, "..", "..") // chunks live under ../chunks relative to the edge entry
  const seen = new Set<string>()
  const queue: Array<{ abs: string; relName: string }> = []
  const entryBody = await readFile(entryPath, "utf8")
  for (const rel of otherChunksOf(entryBody)) {
    queue.push({ abs: join(baseDir, rel), relName: rel })
  }
  const copied: Array<{ srcAbs: string; relName: string }> = []
  while (queue.length > 0) {
    const item = queue.shift()!
    if (seen.has(item.relName)) continue
    seen.add(item.relName)
    copied.push({ srcAbs: item.abs, relName: item.relName })
    try {
      const body = await readFile(item.abs, "utf8")
      for (const rel of otherChunksOf(body)) {
        if (!seen.has(rel)) queue.push({ abs: join(baseDir, rel), relName: rel })
      }
    } catch {
      // missing optional chunk: skip; runtime tolerates absent registrations
    }
  }
  return copied
}

export async function packEdgeHandlers(input: {
  projectDir: string
  routes: EdgeRouteEntry[]
}): Promise<{ count: number }> {
  const { copyTo } = await import("./pack")
  const routes = input.routes.filter((route) => Boolean(route.filePath))
  const serverDir = join(input.projectDir, OUT_DIR, "server")
  await mkdir(serverDir, { recursive: true })

  const rows: Array<{
    id: string
    key: string
    handlerExport: string
    pattern: string
    modulePath: string
  }> = []

  for (const route of routes) {
    const id = slug(route.pathname)
    const entryKey = route.entryKey ?? `middleware_${route.id ?? ""}`
    const handlerExport = route.handlerExport || "handler"
    const ext = extname(route.filePath!) || ".js"
    const moduleFile = `${id}${ext}`
    const moduleFileIndex = `${id}.index.mjs`
    await copyTo(route.filePath!, join(serverDir, moduleFile))

    // Transitive chunk closure, mirrored under chunks/ relative names.
    const chunksDir = join(serverDir, "chunks")
    await mkdir(chunksDir, { recursive: true })
    const closure = await collectChunkClosure(route.filePath!)
    for (const chunk of closure) {
      await copyTo(chunk.srcAbs, join(chunksDir, chunk.relName.replace(/^chunks\//, "")))
    }

    // Siblings first (feed the registry), entry last (consumes it).
    const indexBody = `${closure.map((chunk) => `import ${JSON.stringify(`./chunks/${chunk.relName}`)}\n`).join("")}import ${JSON.stringify(`./${moduleFile}`)}\n`
    await writeFile(join(serverDir, moduleFileIndex), indexBody)

    for (const [rel, abs] of Object.entries(route.assets ?? {})) {
      await copyTo(abs, join(serverDir, rel))
    }
    rows.push({
      id,
      key: entryKey,
      handlerExport,
      pattern: patternFor(route.pathname),
      modulePath: `../server/${moduleFileIndex}`,
    })
  }

  const body = `// @generated by cfnext during cfnext build. Do not edit.
// Dispatches Next edge-runtime routes before the asset fallback.
type EdgeEntryModule = Record<string, unknown>

const routes: Array<{ id: string; key: string; handlerExport: string; pattern: RegExp }> = [
${rows
  .map(
    (row) =>
      `  { id: ${JSON.stringify(row.id)}, key: ${JSON.stringify(row.key)}, handlerExport: ${JSON.stringify(row.handlerExport)}, pattern: new RegExp(${JSON.stringify(row.pattern)}) },`,
  )
  .join("\n")}
]

const loaders: Record<string, () => Promise<EdgeEntryModule>> = {
${rows.map((row) => `  ${JSON.stringify(row.id)}: () => import(${JSON.stringify(row.modulePath)}),`).join("\n")}
}

export async function edgeFetch(
  request: Request,
  ctx?: { waitUntil?: (promise: Promise<void>) => void },
): Promise<Response | null> {
  const { pathname } = new URL(request.url)
  const clean = pathname.length > 1 && pathname.endsWith("/") ? pathname.slice(0, -1) : pathname
  const hit = routes.find((route) => route.pattern.test(clean))
  if (!hit) return null
  const loader = loaders[hit.id]
  if (!loader) return null
  await loader()
  const entries = (globalThis as { _ENTRIES?: Record<string, unknown> })._ENTRIES ?? {}
  const holder = entries[hit.key]
  if (!holder) return null
  const candidate = (holder as { [k: string]: unknown })[hit.handlerExport]
  const handler =
    typeof candidate === "function"
      ? candidate
      : typeof (holder as { default?: unknown }).default === "function"
        ? (holder as { default: unknown }).default
        : null
  if (typeof handler !== "function") return null
  return (handler as (req: Request, c?: unknown) => Promise<Response>)(request, ctx)
}
`

  await writeFile(join(input.projectDir, GENERATED_HANDLERS), body)
  return { count: rows.length }
}

export function edgePackLog(projectDir: string, count: number): string {
  return `[cfnext] bundled ${count} edge route(s) → ${relative(projectDir, join(projectDir, OUT_DIR, "server"))}`
}
