import { mkdir, writeFile } from "node:fs/promises"
import { extname, join } from "node:path"

import { ADAPTER_NAME, OUT_DIR } from "../constants"
import type { CfnextConfig } from "../config"
import { copyTo, type PackOutputs, type PackRouting } from "../pack"
import type { SsrHandlerKind, SsrManifest, SsrManifestHandler } from "./types"

export type SsrManifestInput = {
  outputs: PackOutputs
  routing: PackRouting
  buildId: string
  nextVersion: string
  config: CfnextConfig
}

export type PackSsrInput = SsrManifestInput & {
  projectDir: string
}

export function handlerId(pathname: string, explicit?: string): string {
  if (explicit && explicit.length > 0) return explicit
  const slug = pathname.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "")
  return slug || "root"
}

export function moduleFileName(id: string, filePath?: string): string {
  const ext = extname(filePath ?? "") || ".js"
  return `${id}${ext}`
}

export function buildSsrManifest(input: SsrManifestInput): SsrManifest {
  const groups: Array<{ kind: SsrHandlerKind; items: PackOutputs["appPages"] }> = [
    { kind: "app-page", items: input.outputs.appPages },
    { kind: "app-route", items: input.outputs.appRoutes },
    { kind: "pages", items: input.outputs.pages },
    { kind: "pages-api", items: input.outputs.pagesApi },
  ]

  const handlers: SsrManifestHandler[] = []
  for (const group of groups) {
    for (const item of group.items) {
      const id = handlerId(item.pathname, item.id)
      handlers.push({
        id,
        pathname: item.pathname,
        runtime: item.runtime,
        kind: group.kind,
        module: moduleFileName(id, item.filePath),
      })
    }
  }

  if (input.outputs.middleware) {
    handlers.push({
      id: "middleware",
      pathname: "/_middleware",
      runtime: input.outputs.middleware.runtime === "edge" ? "edge" : "nodejs",
      kind: "middleware",
      module: moduleFileName("middleware", input.outputs.middleware.filePath),
    })
  }

  return {
    adapter: ADAPTER_NAME,
    target: "ssr",
    bun: true,
    openNext: false,
    nodejsCompat: true,
    buildId: input.buildId,
    nextVersion: input.nextVersion,
    handlers,
    prerenders: input.outputs.prerenders.map((item) => item.pathname),
    routing: {
      dynamic: input.routing.dynamicRoutes.map((route) => route.source ?? route.sourceRegex),
    },
  }
}

export function renderSsrRuntime(manifest: SsrManifest): string {
  const loaderLines = manifest.handlers
    .map(
      (handler) =>
        `  ${JSON.stringify(handler.id)}: () => import(${JSON.stringify(`./.cloudflare/server/${handler.module}`)}),`,
    )
    .join("\n")
  return `// Generated by cfnext. Do not edit.
export const handlers = ${JSON.stringify(manifest.handlers, null, 2)}
export const prerenders = ${JSON.stringify(manifest.prerenders, null, 2)}
export const loaders = {
${loaderLines}
}
`
}

export async function packSsrHandlers(input: PackSsrInput): Promise<{ manifest: SsrManifest }> {
  const manifest = buildSsrManifest(input)
  const serverDir = join(input.projectDir, OUT_DIR, "server")
  await mkdir(serverDir, { recursive: true })

  const items = [
    ...input.outputs.appPages,
    ...input.outputs.appRoutes,
    ...input.outputs.pages,
    ...input.outputs.pagesApi,
  ]
  if (input.outputs.middleware?.filePath) {
    items.push({
      pathname: "/_middleware",
      runtime: input.outputs.middleware.runtime === "edge" ? "edge" : "nodejs",
      filePath: input.outputs.middleware.filePath,
      id: "middleware",
    })
  }

  for (const item of items) {
    if (!item.filePath) continue
    const id = handlerId(item.pathname, item.id)
    await copyTo(item.filePath, join(serverDir, moduleFileName(id, item.filePath)))
    if (item.assets) {
      for (const [rel, abs] of Object.entries(item.assets)) {
        await copyTo(abs, join(serverDir, "assets", rel))
      }
    }
  }

  await writeFile(join(input.projectDir, OUT_DIR, "ssr-manifest.json"), JSON.stringify(manifest, null, 2))
  await writeFile(join(input.projectDir, "ssr-runtime.ts"), renderSsrRuntime(manifest))
  return { manifest }
}
